### ISSUE TITLE
部署 annil 时报错 Error: No such file or directory (os error 2) 并且未生成 ./data/config.yaml

### ISSUE THREAD

**Issue by LacLic** [ProjectAnni/anni#40]
部署 annil 时报错 Error: No such file or directory (os error 2) 并且未生成 ./data/config.yaml

部署方法来自 [快速部署](https://anni.rs/guide/deploy.html#%E9%83%A8%E7%BD%B2-annil)

```
$ sudo docker-compose down && sudo docker-compose pull && sudo docker-compose up
[+] Running 2/0
 ✔ Container annil        Removed                                                                                                                                                         0.0s 
 ✔ Network annil_default  Removed                                                                                                                                                         0.1s 
[+] Pulling 1/1
 ✔ annil Pulled                                                                                                                                                                           1.3s 
[+] Running 2/0
 ✔ Network annil_default  Created                                                                                                                                                         0.0s 
 ✔ Container annil        Created                                                                                                                                                         0.0s 
Attaching to annil
annil  | Error: No such file or directory (os error 2)
annil exited with code 0
```

目录结构

```
$ tree .
.
├── compose.yaml
└── data
```

原先以为是 ./data/ 中缺少 config.yaml 导致的报错，```touch ./data/config.yaml``` 后还是同样报错

compose.yaml 内容

```yaml
version: "3"
services:
  annil:
    container_name: annil
    image: ghcr.io/projectanni/annil:latest
    ports:
      - 8061:80/tcp
    volumes:
      - ./data:/app/data
      - /mnt/wd7t/nfs/downloads/anni/annil/library:/library
    restart: unless-stopped
```
